# Generated by Django 5.0.2 on 2024-02-20 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.university', verbose_name='Университет'),
        ),
        migrations.AlterField(
            model_name='taskanswer',
            name='description',
            field=models.TextField(verbose_name='Отклик'),
        ),
        migrations.AlterField(
            model_name='taskanswer',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
