# Generated by Django 5.0.2 on 2024-02-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_alter_task_university_alter_taskanswer_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.CharField(max_length=2, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='direction',
            field=models.CharField(max_length=100, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='university',
            name='university',
            field=models.CharField(max_length=100, verbose_name='Университет'),
        ),
    ]
