# Generated by Django 4.2.8 on 2023-12-11 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_executor', models.BooleanField(default=0)),
                ('is_customer', models.BooleanField(default=0)),
                ('photo', models.ImageField(blank=True, upload_to='profile/')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('balance', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=5.0)),
                ('count_tasks', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
