# Generated by Django 5.0.2 on 2024-02-17 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestask',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_task', to='app.task'),
        ),
        migrations.AlterField(
            model_name='imagestask',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_task', to='app.task'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.direction'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.university'),
        ),
        migrations.AlterField(
            model_name='task',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='task',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.direction', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='task',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.university', verbose_name='ВУЗ'),
        ),
        migrations.AlterField(
            model_name='taskanswer',
            name='task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.task'),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
