# Generated by Django 4.2.8 on 2023-12-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_university_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='direction',
            field=models.CharField(max_length=100),
        ),
    ]
