# Generated by Django 4.2.8 on 2023-12-15 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_task_taskanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='count_active_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
