# Generated by Django 4.2.8 on 2023-12-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_task_taskanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
