# Generated by Django 4.2.8 on 2023-12-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_task_count_active_tasks_alter_task_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='count_active_tasks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
