# Generated by Django 4.2.8 on 2023-12-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_task_count_active_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='count_active_tasks',
        ),
        migrations.AddField(
            model_name='profile',
            name='count_active_tasks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
