# Generated by Django 4.2.8 on 2024-01-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_taskanswer_author_id_alter_taskanswer_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verify',
            field=models.BooleanField(default=False),
        ),
    ]
