# Generated by Django 4.2.8 on 2024-01-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_task_photo_imagestask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagestask',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='tasks/'),
        ),
    ]
