# Generated by Django 4.2.8 on 2024-01-11 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_imagestask_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagestask',
            name='task',
        ),
    ]
