# Generated by Django 4.2.8 on 2024-01-23 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_imagestask_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagestask',
            name='task_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='app.task'),
            preserve_default=False,
        ),
    ]
