# Generated by Django 4.2.8 on 2024-01-23 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_imagestask_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagestask',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_task', to='app.task'),
        ),
    ]
