# Generated by Django 4.2.8 on 2024-01-24 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_imagestask_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='tasks/')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_task', to='app.task')),
            ],
        ),
    ]
