# Generated by Django 5.0.2 on 2024-02-20 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_profile_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_verify',
        ),
    ]
