# Generated by Django 5.0.2 on 2024-02-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_remove_profile_email_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='rating',
            field=models.IntegerField(default=None, verbose_name='Оценка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возвраст'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.FloatField(default=5.0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='contact',
            field=models.TextField(blank=True, null=True, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание профиля'),
        ),
    ]
