# Generated by Django 5.0.2 on 2024-02-28 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_comments_rating_alter_profile_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_customer',
        ),
    ]
